try{
    console.log(x)
}

catch(error){
    console.error(error)
}


finally{
    console.log("this will always execute")
}


console.log("u reached the end ")